# Generated by Django 4.0.10 on 2023-03-24 08:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0007_mymodel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mymodel',
            old_name='name',
            new_name='title',
        ),
        migrations.RemoveField(
            model_name='mymodel',
            name='created_at',
        ),
        migrations.AddField(
            model_name='mymodel',
            name='content',
            field=models.TextField(default=datetime.date(2023, 3, 24)),
            preserve_default=False,
        ),
    ]
