# Generated by Django 4.0 on 2023-03-27 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0010_document_uploaded_at_alter_document_docfile'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='upload',
            field=models.FileField(blank=True, null=True, upload_to='uploads/'),
        ),
    ]
